# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	
    pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2',:tag => "3.0.0",:submodules => true
    pod 'DateTools', '~>1.7.0'
    pod 'SwiftDate', '~> 4.0'
    pod 'SAMKeychain'

  # Pods for CoreKit

  target 'CoreKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
